sudo: required
language: python
python:
  - "2.7"

services:
  - docker

env:
  COMPOSE_VERSION: 1.4.2

install:
  - pip install -r requirements.txt

script:
  - docker-compose build
  - docker-compose up -d

  - docker-compose down

