sudo: required
language: python
python:
  - "3.6"

services:
  - docker

env:
  COMPOSE_VERSION: 1.4.2

install:
  - pip install -r requirements.txt

script:
  - docker-compose build
  - docker-compose up -d
  - python3 ./backend/tests/request_to_backend.py
  - docker-compose down

