sudo: required
language: python
python:
  - "3.6"

services:
  - docker

env:
  COMPOSE_VERSION: 1.4.2

install:
  - pip install requests

script:
  - docker-compose build
  - docker-compose up
  - ./backend/tests/test_request.py
  - ./backend/tests/request_to_backend.py
  - docker-compose down
