sudo: required

services:
  - docker

env:
  COMPOSE_VERSION: 1.4.2

script:
  - docker-compose build
  - docker-compose up -d
  - python ./backend/tests/request_to_backend.py
  - docker-compose down

