version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "9000:9000"
    environment: 
      - APPID:

  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    depends_on:
      - backend
